export type LocationState = {
  name: string;
  townships: string[];
};

export const locationData: LocationState[] = [
  {
    name: "Kachin State",
    townships: [
      "Bhamo",
      "Myitkyina",
      "Mohnyin",
      "Chipwi",
      "Dawthponeyan",
      "Hopin",
      "Hpakant",
      "Injangyang",
      "Kamaing",
      "Kanpaiktee",
      "Khaunglanphu",
      "Lwegye",
      "Machanbaw",
      "Mansi",
      "Mogaung",
      "Momauk",
      "Myohla",
      "Naungmun",
      "Panwa",
      "Pannandin",
      "Putao",
      "Sadon",
      "Shinbweyan",
      "Shwegu",
      "Sinbo",
      "Sumprabum",
      "Tanai",
      "Hsawlaw",
      "Waingmaw",
    ],
  },
  {
    name: "Kayah State",
    townships: [
      "Loikaw",
      "Demoso",
      "Bawlakhe",
      "Hpasawng",
      "Hpruso",
      "Mese",
      "Shadaw",
      "Ywathit",
    ],
  },
  {
    name: "Kayin State",
    townships: [
      "Hpa-an",
      "Kawkareik",
      "Hpapun",
      "Kyainseikgyi",
      "Hlaingbwe",
      "Myawaddy",
      "Thandaunggyi",
      "Bawgali",
      "Paingkyon",
      "Shanywathit",
    ],
  },
  {
    name: "Chin State",
    townships: [
      "Hakha",
      "Tedim",
      "Falam",
      "Kanpetlet",
      "Matupi",
      "Mindat",
      "Paletwa",
      "Rekadarl",
      "Thantlang",
      "Zokhawthar",
    ],
  },
  {
    name: "Sagaing Region",
    townships: [
      "Sagaing",
      "Kalay",
      "Kanbalu",
      "Banmauk",
      "Homalin",
      "Kaleewa",
      "Katha",
      "Hkamti",
      "Khin U",
      "Mawlaik",
      "Monywa",
      "Myinmu",
      "Natmauk",
      "Ngazun",
      "Pale",
      "Phaungpyin",
      "Shwebo",
      "Salingyi",
      "Tamu",
      "Taze",
      "Wetlet",
      "Yinmabin",
      "Ye U",
      "Butsun",
      "Ayadaw",
    ],
  },
  {
    name: "Tanintharyi Region",
    townships: [
      "Dawei",
      "Myeik",
      "Kawthaung",
      "Palaw",
      "Launglon",
      "Kyunsu",
      "Kaleinaung",
      "Yebyu",
      "Tanintharyi",
      "Bokpyin",
      "Khamaukgyi",
    ],
  },
  {
    name: "Bago Region",
    townships: [
      "Bago",
      "Kawa",
      "Taungoo",
      "Daik U",
      "Kyaukkyi",
      "Kyauktaga",
      "Monyo",
      "Nattalin",
      "Pandaung",
      "Paukkhaung",
      "Pyay",
      "Yedashe",
      "Shwetaung",
      "Thayarwady",
      "Thantaung",
      "Thegon",
      "Waw",
      "Zigon",
    ],
  },
  {
    name: "Magway Region",
    townships: [
      "Magway",
      "Salin",
      "Chauk",
      "Aunglan",
      "Sinpaungwe",
      "Kamina",
      "Minhla",
      "Mindon",
      "Myaing",
      "Ngape",
      "Pakokku",
      "Pwintphyu",
      "None",
      "Saw",
      "Seikphyu",
      "Thayet",
      "Yenangyaung",
      "Yesagyo",
      "Taungdwingyi",
      "Gangaw",
    ],
  },
  {
    name: "Mandalay Region",
    townships: [
      "Mahar Aung Myay",
      "Tada U",
      "Pyin Oo Lwin",
      "Amarapura",
      "Aungmyethazan",
      "Chanmyathazi",
      "Kyaukpadaung",
      "Kyaukse",
      "Chanayethazan",
      "Mahlaing",
      "Meiktila",
      "Natogyi",
      "Ngazun",
      "Patheingyi",
      "Yamethin",
      "Thazi",
      "Taungtha",
      "Wundwin",
      "Yatanapon",
      "Singu",
      "Madaya",
      "Thabeikkyin",
      "Pyawbwe",
      "Nyaung U",
    ],
  },
  {
    name: "Mon State",
    townships: [
      "Mawlamyine",
      "Kyaikmaraw",
      "Thaton",
      "Kyaikto",
      "Chaungzon",
      "Khalaw",
      "Mudon",
      "Paung",
      "Ye",
      "Thanbyuzayat",
    ],
  },
  {
    name: "Rakhine State",
    townships: [
      "Sittwe",
      "Thandwe",
      "Ramree",
      "Ann",
      "Buthidaung",
      "Gwa",
      "Kyaukphyu",
      "Kyauktaw",
      "Maungdaw",
      "Minbya",
      "Myebon",
      "Pauktaw",
      "Ponnagyun",
      "Rathedaung",
      "Taunggok",
    ],
  },
  {
    name: "Yangon Region",
    townships: [
      "Ahlone",
      "Bahan",
      "Botataung",
      "Dagon",
      "North Dagon",
      "South Dagon",
      "Dagon Seikkan",
      "East Dagon",
      "Dala",
      "Dawbon",
      "Hmawbi",
      "Kamayut",
      "Kayan",
      "Cocokyun",
      "Kyauktada",
      "Kyauktan",
      "Hlaing",
      "Hlaingthaya",
      "Latha",
      "Mayangone",
      "Mingaladon",
      "Mingalar Taung Nyunt",
      "North Okkalapa",
      "Okkan",
      "Okkalapa",
      "Pabedan",
      "Pazundaung",
      "Sanchaung",
      "Seikgyikanaungto",
      "Thaketa",
      "Thanlyin",
      "Thaikgyi",
      "Thingangyun",
      "Tamwe",
      "Taikkyi",
      "Twante",
      "Yankin",
      "Shwepyitha",
    ],
  },
  {
    name: "Shan State",
    townships: [
      "Taunggyi",
      "Lashio",
      "Tachileik",
      "Kholam",
      "Hopang",
      "Hopong",
      "Kalaw",
      "Kesi",
      "Kunhing",
      "Kyaukme",
      "Kutkai",
      "Langkho",
      "Laukkaing",
      "Loilen",
      "Maukme",
      "Mongpan",
      "Mongton",
      "Mongkhat",
      "Monghsat",
      "Namsang",
      "Namhsan",
      "Namtu",
      "Pinlaung",
      "Pindaya",
      "Pwintphyu",
      "Ywangan",
      "Takaw",
      "Tangyan",
      "Shwenyaung",
      "Muse",
    ],
  },
  {
    name: "Ayeyarwady Region",
    townships: [
      "Pathein",
      "Hinthada",
      "Ngapudaw",
      "Ingapu",
      "Bogale",
      "Danubyu",
      "Pyapon",
      "Kyonpyaw",
      "Kyangin",
      "Kyaiklat",
      "Maubin",
      "Mawlamyinegyun",
      "Myaungmya",
      "Ngathaingchaung",
      "Nyaungdon",
      "Pantanaw",
      "Thabaung",
      "Wakema",
      "Yekyi",
      "Zalun",
    ],
  },
];
