export type Township = {
  code: string;
  name: string;
};

export type NrcState = {
  stateCode: string;
  townships: Township[];
};

export const nrcTypes = [
  { value: "နိုင်", label: "နိုင် (Citizenship)" },
  { value: "ဧည့်", label: "ဧည့် (Associate)" },
  { value: "ပြု", label: "ပြု (Naturalized)" },
] as const;

export const nrcData: NrcState[] = [
  {
    stateCode: "၁", // Kachin State
    townships: [
      { code: "ဗမန", name: "ဗန်းမော်" },
      { code: "မကန", name: "မြစ်ကြီးနား" },
      { code: "မညန", name: "မိုးညှင်း" },
      { code: "ခဖန", name: "ချီဖွေ" },
      { code: "ဒဖယ", name: "ဒေါဖုန်းယန်" },
      { code: "ဟပန", name: "ဟိုပင်" },
      { code: "ဖကန", name: "ဖားကန့်" },
      { code: "အဂယ", name: "အင်ဂျန်းယန်း" },
      { code: "ကမတ", name: "ကာမိုင်း" },
      { code: "ကပတ", name: "ကန်ပိုက်တီ" },
      { code: "ခလဖ", name: "ခေါင်လန်းဖူး" },
      { code: "လဂန", name: "လွယ်ဂျယ်" },
      { code: "မခဘ", name: "မချမ်းဘော" },
      { code: "မစန", name: "မန်းစီ" },
      { code: "မကတ", name: "မိုးကောင်း" },
      { code: "မမန", name: "မိုးမောက်" },
      { code: "မလန", name: "မြို့လှ" },
      { code: "နမန", name: "နောင်မွန်း" },
      { code: "ပဝန", name: "ပန်ဝါ" },
      { code: "ပနဒ", name: "ပန်နန်းဒင်" },
      { code: "ပတအ", name: "ပူတာအို" },
      { code: "ဆဒန", name: "ဆဒုံး" },
      { code: "ရဗယ", name: "ရှင်ဗွေယန်" },
      { code: "ရကန", name: "ရွှေကူ" },
      { code: "ဆဘန", name: "ဆင်ဘို" },
      { code: "ဆပရ", name: "ဆွမ်ပရာဘွမ်" },
      { code: "တနန", name: "တနိုင်း" },
      { code: "တဆလ", name: "ဆော့လော်" },
      { code: "ဝမန", name: "ဝိုင်းမော်" },
    ],
  },
  {
    stateCode: "၂", // Kayah State
    townships: [
      { code: "လကန", name: "လွိုင်ကော်" },
      { code: "ဒမဆ", name: "ဒီးမော့ဆို" },
      { code: "ဘလခ", name: "ဘောလခဲ" },
      { code: "ဖဆန", name: "ဖားဆောင်း" },
      { code: "ဖရဆ", name: "ဖရူးဆို" },
      { code: "မဆန", name: "မဲစဲ့" },
      { code: "ရတန", name: "ရှားတော" },
      { code: "ရပတ", name: "ရွာသစ်" },
    ],
  },
  {
    stateCode: "၃", // Kayin State
    townships: [
      { code: "ဘအန", name: "ဘားအံ" },
      { code: "ကကရ", name: "ကော့ကရိတ်" },
      { code: "ဖပန", name: "ဖာပွန်" },
      { code: "ကအရ", name: "ကြာအင်းဆိပ်ကြီး" },
      { code: "လဘန", name: "လှိုင်းဘွဲ့" },
      { code: "မြဝတ", name: "မြဝတီ" },
      { code: "သတန", name: "သံတောင်ကြီး" },
      { code: "ဘသစ", name: "ဘောဂလီ" },
      { code: "ပယသ", name: "ပိုင်ကျုံ" },
      { code: "ရှနသ", name: "ရှမ်းရွာသစ်" },
    ],
  },
  {
    stateCode: "၄", // Chin State
    townships: [
      { code: "ဟခန", name: "ဟားခါး" },
      { code: "တတန", name: "တီးတိန်" },
      { code: "ဖလန", name: "ဖလန်း" },
      { code: "ကပလ", name: "ကန်ပက်လက်" },
      { code: "မတပ", name: "မတူပီ" },
      { code: "မတန", name: "မင်းတပ်" },
      { code: "ပလဝ", name: "ပလက်ဝ" },
      { code: "ရခတ", name: "ရိခေါဒါရ်" },
      { code: "ထတလ", name: "ထန်တလန်" },
      { code: "ဇခန", name: "ဇုတ်ခွား" },
    ],
  },
  {
    stateCode: "၅", // Sagaing Region
    townships: [
      { code: "စကန", name: "စစ်ကိုင်း" },
      { code: "ကလထ", name: "ကလေး" },
      { code: "ကဘလ", name: "ကန့်ဘလူ" },
      { code: "ဗမန", name: "ဗန်းမောက်" },
      { code: "ဟမလ", name: "ဟုမ္မလင်း" },
      { code: "ကလဝ", name: "ကလေးဝ" },
      { code: "ကထန", name: "ကသာ" },
      { code: "ခတန", name: "ခန္တီး" },
      { code: "ခဥန", name: "ခင်ဦး" },
      { code: "မမန", name: "မော်လိုက်" },
      { code: "မမတ", name: "မုံရွာ" },
      { code: "မရန", name: "မြင်းမူ" },
      { code: "နတန", name: "နတ်မောက်" },
      { code: "ငဇန", name: "ငါန်းဇွန်" },
      { code: "ပလဘ", name: "ပုလဲ" },
      { code: "ဖလန", name: "ဖောင်းပြင်" },
      { code: "ရဥန", name: "ရွှေဘို" },
      { code: "ဆကန", name: "ဆားလင်းကြီး" },
      { code: "တမန", name: "တမူး" },
      { code: "တဆန", name: "တန့်ဆည်" },
      { code: "ဝသန", name: "ဝက်လက်" },
      { code: "ယမသ", name: "ယင်းမာပင်" },
      { code: "ယအန", name: "ရေဦး" },
      { code: "ဘတလ", name: "ဘုတ်ဆုံ" },
      { code: "အယတ", name: "အရာတော်" },
    ],
  },
  {
    stateCode: "၆", // Tanintharyi Region
    townships: [
      { code: "ထဝန", name: "ထားဝယ်" },
      { code: "မြိတ", name: "မြိတ်" },
      { code: "ကသန", name: "ကော့သောင်း" },
      { code: "ပလန", name: "ပုလော" },
      { code: "လလန", name: "လောင်းလုံ" },
      { code: "ကရသ", name: "ကျွန်းစု" },
      { code: "ကခန", name: "ကလိန်အောင်" },
      { code: "ရဖန", name: "ရေဖြူ" },
      { code: "တနသ", name: "တနင်္သာရီ" },
      { code: "ဘပန", name: "ဘုတ်ပြင်း" },
      { code: "ခမခ", name: "ခမောက်ကြီး" },
    ],
  },
  {
    stateCode: "၇", // Bago Region
    townships: [
      { code: "ပခန", name: "ပဲခူး" },
      { code: "ကဝန", name: "ကဝ" },
      { code: "တငန", name: "တောင်ငူ" },
      { code: "ဒဥန", name: "ဒိုက်ဦး" },
      { code: "ကကန", name: "ကျောက်ကြည့်" },
      { code: "ကတန", name: "ကျောက်တံခါး" },
      { code: "မညန", name: "မိုးညို" },
      { code: "နတလ", name: "နတ်တလင်း" },
      { code: "ပတန", name: "ပန်းတောင်း" },
      { code: "ပဥန", name: "ပေါက်ခေါင်း" },
      { code: "ပြည်", name: "ပြည်" },
      { code: "ရတာ", name: "ရေတာရှည်" },
      { code: "ရသန", name: "ရွှေတောင်" },
      { code: "သဝတ", name: "သာယာဝတီ" },
      { code: "သကန", name: "သံတောင်" },
      { code: "သဇန", name: "သည်ကုန်း" },
      { code: "ဝနတ", name: "ဝေါ" },
      { code: "ဇတန", name: "ဇီးကုန်း" },
    ],
  },
  {
    stateCode: "၈", // Magway Region
    townships: [
      { code: "မကန", name: "မကွေး" },
      { code: "စလန", name: "စလင်း" },
      { code: "ခမန", name: "ချောာင်းဦး" },
      { code: "အလန", name: "အောင်လံ" },
      { code: "စဖန", name: "ဆင်ပေါင်ဝဲ" },
      { code: "ကမန", name: "ကမေန" },
      { code: "မလန", name: "မင်းလှ" },
      { code: "မတန", name: "မင်းတုန်း" },
      { code: "မမန", name: "မြိုင်" },
      { code: "ငဖန", name: "ငဖဲ" },
      { code: "ပခက", name: "ပခုက္ကူ" },
      { code: "ပဖန", name: "ပွင့်ဖြူ" },
      { code: "စကန", name: "စဲကုိ" },
      { code: "ဆဖန", name: "ဆอ" },
      { code: "ဆတန", name: "ဆိပ်ဖြူ" },
      { code: "သရန", name: "သရက်" },
      { code: "ရနခ", name: "ရေနံချောင်း" },
      { code: "ရစကြ", name: "ရေစကြို" },
      { code: "တတက", name: "တောင်တွင်းကြီး" },
      { code: "ဂံဂော", name: "ဂန့်ဂေါ" },
    ],
  },
  {
    stateCode: "၉", // Mandalay Region
    townships: [
      { code: "မရမ", name: "မဟာအောင်မြေ" },
      { code: "တကန", name: "တံတားဦး" },
      { code: "ပကခ", name: "ပြင်ဦးလွင်" },
      { code: "အမရ", name: "အမရပူရ" },
      { code: "အဆန", name: "အောင်မြေသာစံ" },
      { code: "ခမသ", name: "ချမ်းမြသာစည်" },
      { code: "ကပတ", name: "ကျောက်ပန်းတောင်း" },
      { code: "ကသန", name: "ကျောက်ဆည်" },
      { code: "မဟမ", name: "ချမ်းအေးသာစံ" },
      { code: "မလန", name: "မလှိုင်" },
      { code: "မထလ", name: "မိတ္ထီလာ" },
      { code: "နတတ", name: "နထိုးကြီး" },
      { code: "ငဇန", name: "ငါန်းဇွန်" },
      { code: "ပတက", name: "ပုသိမ်ကြီး" },
      { code: "ရမသ", name: "ရမည်းသင်း" },
      { code: "သစန", name: "သာစည်" },
      { code: "တထန", name: "တောင်သာ" },
      { code: "ဝတန", name: "ဝမ်းတွင်း" },
      { code: "ရမန", name: "ရတနာပုံ" },
      { code: "စငန", name: "စဉ့်ကူး" },
      { code: "မတရ", name: "မတ္တရာ" },
      { code: "သပက", name: "သပိတ်ကျင်း" },
      { code: "ပျေဘ", name: "ပျော်ဘွယ်" },
      { code: "ညဥန", name: "ညောင်ဦး" },
    ],
  },
  {
    stateCode: "၁၀", // Mon State
    townships: [
      { code: "မလမ", name: "မော်လမြိုင်" },
      { code: "ကမရ", name: "ကျိုက်မရော" },
      { code: "သထန", name: "သထုံ" },
      { code: "ခဇန", name: "ကျိုက်ထို" },
      { code: "ချဆန", name: "ချောင်းဆုံ" },
      { code: "ကလအ", name: "ကလော့" },
      { code: "မဒန", name: "မုဒုံ" },
      { code: "ပနတ", name: "ပေါင်" },
      { code: "ရဖြူ", name: "ရေး" },
      { code: "သဖြူ", name: "သံဖြူဇရပ်" },
    ],
  },
  {
    stateCode: "၁၁", // Rakhine State
    townships: [
      { code: "စတန", name: "စစ်တွေ" },
      { code: "သတန", name: "သံတွဲ" },
      { code: "ရဗန", name: "ရမ္ဘီး" },
      { code: "အမန", name: "အမ်း" },
      { code: "ဗဓတ", name: "ဘူးသီးတောင်" },
      { code: "ဂဝန", name: "ဂွ" },
      { code: "ကပန", name: "ကျောက်ဖြူ" },
      { code: "ကတန", name: "ကျောက်တော်" },
      { code: "မအန", name: "မောင်တော" },
      { code: "မဥန", name: "မင်းပြား" },
      { code: "မြေပုံ", name: "မြေပုံ" },
      { code: "ပနတ", name: "ပေါက်တော" },
      { code: "ပဏတ", name: "ပုဏ္ဏားကျွန်း" },
      { code: "ရသတ", name: "ရသေ့တောင်" },
      { code: "တငပ", name: "တောင်ကုတ်" },
    ],
  },
  {
    stateCode: "၁၂", // Yangon Region
    townships: [
      { code: "အလန", name: "အလုံ" },
      { code: "ဗဟန", name: "ဗဟန်း" },
      { code: "ဗတထ", name: "ဗိုလ်တထောင်" },
      { code: "ဒဂန", name: "ဒဂုံ" },
      { code: "ဒဂမ", name: "ဒဂုံမြို့သစ်မြောက်ပိုင်း" },
      { code: "ဒဂသ", name: "ဒဂုံမြို့သစ်တောင်ပိုင်း" },
      { code: "ဒဂဆ", name: "ဒဂုံမြို့သစ်ဆိပ်ကမ်း" },
      { code: "ဒဂတ", name: "ဒဂုံမြို့သစ်အရှေ့ပိုင်း" },
      { code: "ဒလန", name: "ဒလ" },
      { code: "ဒပန", name: "ဒေါပုံ" },
      { code: "ကမတ", name: "မှော်ဘီ" },
      { code: "ကမရ", name: "ကမရွတ်" },
      { code: "ခယန", name: "ခရမ်း" },
      { code: "ကကက", name: "ကိုးကိုးကျွန်း" },
      { code: "ကတတ", name: "ကျောက်တံတား" },
      { code: "ကတန", name: "ကျောက်တန်း" },
      { code: "လမန", name: "လှိုင်" },
      { code: "လကန", name: "လှိုင်သာယာ" },
      { code: "လသာ", name: "လသာ" },
      { code: "မဘန", name: "မယန်းကုန်း" },
      { code: "မဂဒ", name: "မင်္ဂလာဒုံ" },
      { code: "မဂတ", name: "မင်္ဂလာတောင်ညွန့်" },
      { code: "မရက", name: "မြောက်ဥက္ကလာပ" },
      { code: "ဥကမ", name: "ဥက္ကံ" },
      { code: "ဥကတ", name: "ဥက္ကလာပ" },
      { code: "ပဘတ", name: "ပန်းဘဲတန်း" },
      { code: "ပဇတ", name: "ပုဇွန်တောင်" },
      { code: "စကန", name: "စမ်းချောင်း" },
      { code: "ဆကန", name: "ဆိပ်ကြီးခနောင်တို" },
      { code: "သကတ", name: "သာကေတ" },
      { code: "သခန", name: "သန်လျင်" },
      { code: "သကန", name: "သိုက်ကြီး" },
      { code: "သကြတ", name: "သင်္ဃန်းကျွန်း" },
      { code: "တမန", name: "တာမွေ" },
      { code: "တခန", name: "တိုက်ကြီး" },
      { code: "တတန", name: "တွံတေး" },
      { code: "ရကန", name: "ရန်ကင်း" },
      { code: "ရကတ", name: "ရွှေပြည်သာ" },
    ],
  },
  {
    stateCode: "၁၃", // Shan State
    townships: [
      { code: "တကန", name: "တောင်ကြီး" },
      { code: "လရန", name: "လရှိုး" },
      { code: "မဆတ", name: "တာချီလိတ်" },
      { code: "ခလန", name: "ခိုလမ်" },
      { code: "ဟပန", name: "ဟိုပန်" },
      { code: "ဟပတ", name: "ဟိုပုံး" },
      { code: "ကလန", name: "ကလော" },
      { code: "ကလတ", name: "ကဲသီး" },
      { code: "ကလသ", name: "ကွန်ဟိန်း" },
      { code: "ကသန", name: "ကျောက်မဲ" },
      { code: "ကမန", name: "ကွတ်ခိုင်" },
      { code: "လအန", name: "လင်းခေ" },
      { code: "လခန", name: "လောက်ကိုင်" },
      { code: "လအလ", name: "လွိုင်လင်" },
      { code: "မမန", name: "မောက်မယ်" },
      { code: "မပန", name: "မိုင်းပန်" },
      { code: "မတန", name: "မိုင်းတုံ" },
      { code: "မမတ", name: "မိုင်းခတ်" },
      { code: "မသန", name: "မိုင်းဆတ်" },
      { code: "နဆန", name: "နမ့်ဆန်" },
      { code: "နသန", name: "နမ့်စံ" },
      { code: "နမတ", name: "နမ္မတူ" },
      { code: "ပဘန", name: "ပင်လောင်း" },
      { code: "ပပက", name: "ပင်းတယ" },
      { code: "ပတန", name: "ပွင့်ဖြူ" },
      { code: "ရရန", name: "ရွာငန်" },
      { code: "တခလ", name: "တာကဝ" },
      { code: "တယန", name: "တန့်ယန်း" },
      { code: "ရငန", name: "ရွှေညောင်" },
      { code: "မူဆယ်", name: "မူဆယ်" },
    ],
  },
  {
    stateCode: "၁၄", // Ayeyarwady Region
    townships: [
      { code: "ပသန", name: "ပုသိမ်" },
      { code: "ဟသတ", name: "ဟင်္သာတ" },
      { code: "ငပတ", name: "ငပုတော" },
      { code: "အဂပ", name: "အင်္ဂပူ" },
      { code: "ဘကလ", name: "ဘိုကလေး" },
      { code: "ဓနဖ", name: "ဓနုဖြူ" },
      { code: "ဖပန", name: "ဖျာပုံ" },
      { code: "ကပယ", name: "ကျုံပျော်" },
      { code: "ကကန", name: "ကြံခင်း" },
      { code: "ကလန", name: "ကျိုက်လတ်" },
      { code: "မအပ", name: "မအူပင်" },
      { code: "မအတ", name: "မော်လမြိုင်ကျွန်း" },
      { code: "မမန", name: "မြောင်းမြ" },
      { code: "ငသက", name: "ငသိုင်းချောင်း" },
      { code: "ညနတ", name: "ညောင်တုန်း" },
      { code: "ပတန", name: "ပန်းတနော်" },
      { code: "သာပေါင်း", name: "သာပေါင်း" },
      { code: "ဝခမ", name: "ဝါးခယ်မ" },
      { code: "ရကန", name: "ရေကြည်" },
      { code: "ဇလွန်", name: "ဇလွန်" },
    ],
  },
];

/**
 * Utility function to validate a formatted Myanmar NRC string.
 * Example format: "၁၂/လမန(နိုင်)၁၂၃၄၅၆"
 */
export function isValidNrc(nrcString: string): boolean {
  const nrcRegex = /^(၁[၀-၄]|[၁-၉])\/[က-အ]{1,6}\((နိုင်|ဧည့်|ပြု|သ|သီ)\)[၀-၉]{၆}$/;
  return nrcRegex.test(nrcString.trim());
}