server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/digital_wallet_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

jwt:
  secret: ${JWT_SECRET:change-this-secret-key-should-be-very-long}
  expiration-millis: 86400000

infinireach:
  api-key: ${INFINIREACH_API_KEY:smsrelay_cf1c5b8e8e091292bb1fce45b5e2215cc32858cc95324510044cd4fec0d38dd1}
  endpoint: https://api.infinireach.io/api/v1/messages

logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    com.example.digitalwallet: DEBUG
